name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Generate Markdown report with local action
        id: generate-sarif-md
        uses: ./.
        with:
          file-path: test-data/qodana.sarif.json
          output-markdown: generated/report.md
          add-job-summary: true

      - name: Verify report artifact
        run: |
          test -f generated/report.md
          head -n 5 generated/report.md


      - name: Create or update comment comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --edit-last \
            --create-if-none \
            --body "${{ steps.generate-sarif-md.outputs.markdown }}"